### ISSUE TITLE
🎟️ Use OpenAPI in Working Mode

### ISSUE THREAD

**Issue by rahaaatul** [aistra0528/Hail#118]
# Open API
> Due to the exclusivity nature, user could only use one Android DPC app at a time, and price of switching DPC is far too heavy. To encourage active exploration and broader development in the capabilities of DPC and therefore better benefit users,
[Island](https://github.com/oasisfeng/island)/[Insular](https://gitlab.com/secure-system/Insular) is devoted to build an open collaboration for community developers, either in development of this project or opening DPC capabilities to 3rd-party apps via open API. Island/ Insular itself will not focus on the rich set of features, but mainly focuses on building a powerful engine as an open platform for much more apps from the community.
Starting from the first public version of Island/Insular, all APIs are open to 3rd-party apps with the standard runtime-permission of Android as user authorization. Developers can start building apps now to take advantage of the Island open APIs.
The protocol of all APIs are well defined and maintained in the [class "Api"](https://gitlab.com/secure-system/Insular/-/blob/dev-ci/shared/src/main/java/com/oasisfeng/island/api/Api.java).

# Reason

1. If I use Hail as device owner, I can't use other apps to create or manage **Work Profile**.
2. If I use dhizuku as device owner; I can't create **Work Profile** with other apps.
3. If I use other apps like [Island](https://github.com/oasisfeng/island)/[Insular](https://gitlab.com/secure-system/Insular)/[Shelter](https://gitea.angry.im/PeterCxy/Shelter) which create and manage Work profiles; I can't use hail or dhizuku as device owner.
4. If I can't use hail as device owner that means I can't freeze a lot of system apps (vivo), which needs device owner to freeze those apps and shizuku simply can't do it. And if I go that route, I can't use Work Profile which I really need.

**Comment by rahaaatul** [comment]
Please @aistra0528 , consider adding this to Hail.

**Comment by andy-math** [comment]
Island的Open API存在三个比较明显的困难：
1. 它没有开放基于dpm.isApplicationHidden的API，导致app冻结状态难以观测
2. 它使用android permissions进行权限管理，与shizuku/dhizuku的通讯方式不太相同
3. 延续第2点，它使用ordered broadcast进行api调用，也与shizuku/dhizuku的通讯不太相同
不管怎样，我借鉴了Island的Hacks，fork了一个Island适配，欢迎尝试

**Comment by andy-math** [comment]
有趣的是Island除了Open API之外，还有某种"open" api: 
https://github.com/oasisfeng/island/blob/master/open/src/main/java/com/oasisfeng/island/DelegatedScopeAuthorization.kt
它提供的delegatedScope授权与Dhizuku的效果基本一致，不过比Dhizuku限制更多

**Comment by rahaaatul** [comment]
@andy-math it'd be better if you could speak English, so I could understand you better. 
But what I understood from the translation is that it's not like Shizuku and dhizuku? And it's restrictive. How?

And how's your fork different?

Thank you.

**Comment by andy-math** [comment]
Shizuku and Dhizuku use android cross-process binder method, which is approximate synchronous rather than asynchronous. Hail's root mode / device owner mode are also synchronized. The Open API uses broadcast-based calls, which are more asynchronous, which is not a "perfect" fit for Hail, which is currently mainly synchronous.
On the other hand, shizuku provides full adb permissions, and dhizuku provides full device owner permissions, while Open API provides only limited permissions, including freezing, unfreezing, and launching the app. it does not provide a way to call isApplicationHidden, which makes it difficult for HAIL to observe whether the app has been frozen.
While it's possible to fork and extend the Open API, I don't think it's a good idea to adapt the software to a personal forked version of the API

**Comment by andy-math** [comment]
My fork adds two commits, one of which uses java reflection to check if the app is frozen without needing the isApplicationHidden permission, this method comes from the island source code. The other commit implements a call to the Open API with a permission request and an asynchronous broadcast.
Known limitations:
1. the result of the permission request is asynchronous, in order to minimize code modification, therefore no further response to the success of the request is made, and the island mode needs to be manually selected again after a successful permission request.
2. in order to return the result of an asynchronous call in a synchronized function, a separate thread had to be used at the broadcast to get the result, blocking the main thread until the call was finished. In order to prevent the main thread from going unresponsive, the API call timeout is considered a failure and the timeout limit had to be chosen very carefully.
3. Lock screen functionality is not supported (missing api)
I've tried to optimize the api broadcast as much as possible following Island's hints, but blocking to do asynchronous work in synchronous style code is difficult and more refactoring is needed to improve the current situation.

**Comment by andy-math** [comment]
DelegatedScopeAuthorization is island's way of authorizing tools like app ops, with permission validation via dpm's RestrictionsReceiver and authorization via dpm's delegatedScope, very similar to dhizuku.
The current island can provide:
1. full unfreeze, freeze, isApplicationHidden permissions
2. lock screen
3. app ops
This ability is only in the code, I haven't found any documentation on it, and the latest app ops tool seems to have removed support for island at the moment.
While delegatedScope provides more, synchronized, dhizuku-like permissions, it's not part of the open api, and island's fork isn't guaranteed to maintain this part, and I'm not inclined to get island permissions this way.

Maybe in addition to device owner, we need phizuku that can provide work profile authorization :)
