### ISSUE TITLE
Frozen apps still trying to connect to internet

### ISSUE THREAD

**Issue by diegantobass** [aistra0528/Hail#225]
My bank app is frozen with hail through the shizuku method. Yet I keep seeing requests going out from this app through my firewall (RethinkDNS). Is the app active? Am I misunderstanding something?

**Comment by advait404** [comment]
Hi, I was in this exact situation.

Try to turn off the 'background data' option for the app in its settings. This stops the frozen app from making network calls

**Comment by chaoscreater** [comment]
What if you suspend the app?

And what if you disable app via root method?

**Comment by advait404** [comment]
Suspend allows background network connections.

Shizuku-disable fully turns off the app, so no internet calls.

**Comment by chaoscreater** [comment]
> Suspend allows background network connections.
> 
> Shizuku-disable fully turns off the app, so no internet calls. Root-disable should do the same thing.

If Shizuku-disable fully turns off the app, then why would there be a need to turn off background data as per your previous comment? I guess what I'm trying to understand is, is this really a Hail issue, or is this more of a Shizuku issue? Doesn't Hail just use the Shizuku API to pass whatever it is that you're trying to do to Shizuku? It's not like Hail is actually doing the disabling/enabling itself. That's my understanding anyway.

**Comment by advait404** [comment]
You won't need to turn off background data if you use disable method. With suspend method, you ideally should turn it off to prevent apps from using the Internet when suspended. Atleast that's what I found out from my limited testing.

I'm not really sure which app is responsible for having this issue. Maybe its even the expected behaviour for suspended apps. I think it info about it should be included in the hail readme so people can choose which method is suitable for them.

**Comment by RohitSurwase** [comment]
I am observing the same behaviour. I have suspended the app using Device Owner but the app still showing network activity in the background.
